### ISSUE TITLE
'space-ACPC' entity in `create_mni_montage()` doesn't apply to release data

### ISSUE THREAD

**Issue by qian-chu** [Cogitate-consortium/iEEG-data-release#2]
Data to be released should have coordinates and labels reported in fsaverage space but `create_mni_montage()` still looks for 'space-ACPC':
https://github.com/Cogitate-consortium/iEEG-data-release/blob/602790d1eb50c7e65fff6a4204d337c5c3a30c12/HelperFunctions.py#L1270-L1271

**Comment by qian-chu** [comment]
BIDS' categorization of templates: (esp. MNI152 vs fsaverage)
https://bids-specification.readthedocs.io/en/latest/appendices/coordinate-systems.html#standard-template-identifiers

**Comment by AlexLepauvre** [comment]
I've removed it now based on the latest decisions of data sharing
